CREATE TABLE COMPANY
(
    COMPANY_NAME VARCHAR(30) PRIMARY KEY,
    ADMIN_USERNAME VARCHAR(30) NOT NULL,
    ADMIN_PASSWORD VARCHAR(30) NOT NULL,
    CONSTRAINT admin_username_unique
        UNIQUE (ADMIN_USERNAME),
    CONSTRAINT admin_password_unique
        UNIQUE (ADMIN_PASSWORD)
);

CREATE TABLE MOTOR
(
    MODEL VARCHAR(30) NOT NULL,
    NUM_PLATE INTEGER(15) PRIMARY KEY,
    CONSTRAINT motor_num_plate_unique
        UNIQUE (NUM_PLATE)
);

CREATE TABLE MEMBERSHIP
(
    MEMBERSHIP_ID INTEGER(15) PRIMARY KEY,
    CUSTOMER_ID INTEGER(15) NOT NULL,
    ANNUAL_FEE FLOAT(10) NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    NUM_OF_USE INTEGER(5) NOT NULL,
    CONSTRAINT membership_id_unique
        UNIQUE (MEMBERSHIP_ID)
);
CREATE TABLE USER
(
    USER_ID INTEGER(15) PRIMARY KEY,
    USERNAME VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(30) NOT NULL,
    DOB DATE,
    ADDRESS VARCHAR(50),
    NAME VARCHAR(30) NOT NULL,
    CONSTRAINT user_username_unique UNIQUE (USERNAME),
    CONSTRAINT user_id UNIQUE (USER_ID),
    CONSTRAINT USER_PKEY PRIMARY KEY(USER_ID)
);

CREATE TABLE CUSTOMER
(
    USER_ID INTEGER(15) NOT NULL, 
    MOTOR_NUM INTEGER(15) NOT NULL,
    MEMBER_ID INTEGER(15) NOT NULL,
    CONSTRAINT customer_member_id_unique
        UNIQUE (MEMBER_ID),
    CONSTRAINT CUST_PKEY
        PRIMARY KEY (USER_ID),
    CONSTRAINT CUST_FKEY 
        FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    CONSTRAINT customer_motor_fk
        FOREIGN KEY (MOTOR_NUM) REFERENCES MOTOR(NUM_PLATE),
    CONSTRAINT customer_membership_fk
        FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERSHIP(MEMBERSHIP_ID)
);


CREATE TABLE PROFESSIONAL
(
    USER_ID INTEGER(15)  NOT NULL,
    SERVICE_ID INTEGER(15),
    CONSTRAINT PRO_UNIQUE_SERVICE 
        UNIQUE (SERVICE_ID),
    CONSTRAINT PRO_PKEY
        PRIMARY KEY (USER_ID),
    CONSTRAINT PRO_FKEY 
        FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);


CREATE TABLE SERVICE
(
    SERVICE_ID INTEGER(15) PRIMARY KEY,
    PROFESSIONAL_ID INTEGER(15) NOT NULL,
    CUSTOMER_ID INTEGER(15) NOT NULL,
    SERVICE_NAME VARCHAR(30) NOT NULL,
    PRICE INTEGER(5) NOT NULL,
    PROFESSIONAL_ACCEPTED TINYINT(1) NOT NULL,
    IS_PAID TINYINT(1) NOT NULL,
    CONSTRAINT service_professional_fk_1
        FOREIGN KEY (PROFESSIONAL_ID) REFERENCES PROFESSIONAL(USER_ID),
    CONSTRAINT service_customer_fk
        FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(USER_ID)
);


CREATE TABLE REVIEW
(
    REVIEW_ID INTEGER(10) PRIMARY KEY,
    CUSTOMER_ID INTEGER(15) NOT NULL,
    SERVICE_ID INTEGER(15) NOT NULL,
    RATING INTEGER(2) NOT NULL,
    REVIEW VARCHAR(50),
    CONSTRAINT review_customer_fk
        FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(USER_ID),
    CONSTRAINT review_service_fk
        FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE(SERVICE_ID)
);